### ISSUE TITLE
Spotify Issue

### ISSUE THREAD

**Issue by DracoClaw** [Killerjet101/open-in-app#1]
When a spotify link is sent, it creates an embeded player. Clicking play in this will play the music in client and not in the spotify app.

Clicking the button in this embed that says "Play on Spotify" opens your browser and not the Spotify app.

Clicking the Spotify logo in this embed, or any elements, brings you to the browser and not the spotify app.

**Comment by Killerjet101** [comment]
In order for this plugin to work, you have to click the link. Using the embed won't work with the plugin because the embed is created by Discord.
