### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Davoleo** [Killerjet101/open-in-app#2]
Got this while navigating in discord I think
![image](https://user-images.githubusercontent.com/24458276/126755947-7d12121f-7082-4c45-977f-3ca4fb27621c.png)

**Comment by Killerjet101** [comment]
Ok thank you! I'll go ahead and look into it. I'll probably have a fix for it before the end of this month but no promises since I have been busy with school as well lol.
